config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'loans/new'
  resources :books
  resources :users
  resources :loans



  # Session routes
	get 'login' => 'session#new'
	post 'login' => 'session#create'
	delete 'logout' => 'session#destroy'
	get 'logout' => 'session#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  
	has_secure_password
	has_many :loans
	has_many :books, through: :loans

	

	def self.search(search)
  		#where("last_name LIKE ?", "%#{search}%")
  		apellidos = where("last_name LIKE ?", "%#{search}%")
  		dnis = where("dni LIKE ?", "%#{search}%")
  		tipos = where("role LIKE ?", "%#{search}%")
		User.from("(#{apellidos.to_sql} UNION #{dnis.to_sql} UNION #{tipos.to_sql}) AS users")
	end	

	def student?
    	self.role == 'Alumno'
  	end

  	def librarian?
   		self.role == 'Bibliotecario'
 	end

 	def preceptor?
   		self.role == 'Preceptor'
 	end

 	def professor?
   		self.role == 'Docente'
 	end

##### SEGÚN EL VALOR QUE SE INGRESA ES LO QUE SE VE
	#def rol
	#	roles = {"librarian" => "Bibliotecario", "preceptor" => "Preceptor", "student" => "Alumno", "professor" => "Docente"}
	#	roles[self.role]
	#end

 	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show,:edit,:update,:destroy]

  load_and_authorize_resource
 
 def index
    @users = User.all

    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def show
  end

  def new
    @user = User.new
    
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :dni, :email, :telephone, :role, :password, :password_confirmation)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!------------------------------- FORMULARIO DE USUARIOS ---------------------------------------->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
        <% if @user.new_record? %>
          <div class="card-header font-weight-bold">Agregar Usuario</div>
        <% else %>
          <div class="card-header font-weight-bold">Editar Usuario</div>
        <% end %>
        
          <%= form_for @user do |f| %>
            <div class="card-body">
               <div class="form-group">
                <%= f.label :Apellido %>
                <%= f.text_field :last_name, class: "form-control", autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label :Nombre %>
                <%= f.text_field :first_name, class: "form-control", autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label :DNI %>
                <%= f.number_field :dni, class: "form-control" %>
              </div>
              
              <div class="form-group">
                <%= f.label :Email %>
                <%= f.email_field :email, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :Teléfono %>
                <%= f.phone_field :telephone, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :Tipo_de_usuario %>
               
                <%= f.select(:role, options_for_select(([[ 'Alumno', 'Alumno'] , [ 'Docente','Docente'] , [ 'Preceptor', 'Preceptor']]), @user.role))%>
              </div>
              <div class="form-group">
                <%= f.label :Contraseña%>
                <%= f.password_field :password, class: "form-control", autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label :Confirmar_Contraseña%>
                <%= f.password_field :password_confirmation, class: "form-control", autofocus: true %>
              </div>
            </div>

            <div class="card-footer text-right">
              <%= link_to "Cancelar", users_path, class: "btn btn-outline-dark" %>
              <% if @user.new_record? %>
                <%= f.submit "Crear usuario" , class: "btn btn-success" %>
                <% else %>
                <%= f.submit "Guardar cambios" , class: "btn btn-secondary" %>
              <% end %>
            </div>

          <% end %>

      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<%= render "users/form" %>

app/views/users/index.html.erb
<%= render "navegacion/navbar"%>


<div class="books-page">
  <div class="container">
      <div class="text-right"><%= link_to "Agregar Usuario", new_user_path, class: "btn btn-outline-primary rounded-0" %>
      </div>
   
    <h3> USUARIOS </h3>

    <%= form_tag(users_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscar Usuario" %>
      <%= submit_tag "Buscar" %>
    <% end %>



    <% @users.each do |user| %>
    <div class="book card flex-sm-row align-items-center align-items-sm-start mt-5">
        <div class="card-body">
          <h4 class="card-title"> <strong> <%= user.last_name %> <%= user.first_name %> </strong></h4>
          <p class="card-text">Contacto: <%= user.email%> | <%= user.telephone%> </p>
          <h5><strong><%= user.role %></strong></h5>
          <h6>N° de Usuario: <%= user.id %></h6>

          <%= link_to "Detalles", user, class: "btn btn-info" %>

          <% if can? :edit, user %>
           <%= link_to "Editar", edit_user_path(user), class: "btn btn-secondary" %>
          <% end %>
          <% if can? :edit, user %>
            <%= link_to "Eliminar", user, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este usuario?" } %>
          <% end %>

        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/users/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, users_path, class: "btn btn-link" %>

    <header class="main">
      <h2>Detalles del Usuario</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
   
      <div class="book-details">
        
        <dl>
          <dt>ID</dt>
          <dd><%= @user.id %></dd>
          <dt>Apellido</dt>
          <dd><%= @user.last_name %></dd>
          <dt>Nombre</dt>
          <dd><%= @user.first_name %></dd>
          <dt>DNI</dt>
          <dd><%= @user.dni %></dd>
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
          <dt>Teléfono</dt>
          <dd><%= @user.telephone %></dd>
          <dt>Tipo de Usuario</dt>
          <dd><%= @user.role %></dd>
        </dl>
        
      </div>
    </div>
  </div>
</div>