config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'loans/new'
  resources :books
  resources :users
  resources :loans



  # Session routes
	get 'login' => 'session#new'
	post 'login' => 'session#create'
	delete 'logout' => 'session#destroy'
	get 'logout' => 'session#destroy'

end

app/models/book.rb
class Book < ApplicationRecord
	has_many :loans
	has_many :users, through: :loans

	before_validation :set_state, on: :create

##### DISPONIBILIDAD DEL LIBRO SEGÚN PRÉSTAMO ACTIVO
	def available?
		(loans.where(state: "actived").or(loans.where(state: "expired"))).count == 0
	end

##### DISPONIBILIDAD DEL LIBRO
	def available
		if self.available?
			self.state = "available"
			dispo = {"available" => "Disponible"}
			dispo[self.state]
		else
			self.state = "not available"
			no_dispo = {"not available" => "No Disponible"}
			no_dispo[self.state]
		end
	end

##### ESTADO POR DEFECTO
	def set_state
	    self.state = "available"
	    dispo = {"available" => "Disponible"}
		dispo[self.state]
	end

##### SEGÚN EL VALOR QUE SE INGRESA ES LO QUE SE VE
	#def estado
	#	estados = {"available" => "Disponible", "not available" => "No Disponible"}
	#	estados[self.state]
	#end


	def self.search(search)
  		authors = where("author LIKE ?", "%#{search}%")
  		names = where("name LIKE ?", "%#{search}%")
  		isbns = where("isbn LIKE ?", "%#{search}%")
		Book.from("(#{authors.to_sql} UNION #{names.to_sql} UNION #{isbns.to_sql}) AS books")

	end	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show,:edit,:update,:destroy]

  load_and_authorize_resource

  def index
    @books = Book.all

   if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    else
      @books = Book.all.order('created_at DESC')
    end
  end

    


  def show

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def book_params
      params.require(:book).permit(:isbn, :name, :author, :tag, :published_at, :state)
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def find_book
    @book = Book.find(params[:id])
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<!------------------------------- FORMULARIO DE LIBROS ---------------------------------------->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
        <% if @book.new_record? %>
          <div class="card-header font-weight-bold">Agregar Libro</div>
        <% else %>
          <div class="card-header font-weight-bold">Editar Libro</div>
        <% end %>
        
        <%= form_for @book do |f| %>
        <div class="card-body">
           <div class="form-group">
            <%= f.label :Isbn %>
            <%= f.number_field :isbn, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :Titulo %>
            <%= f.text_field :name, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :Autor %>
            <%= f.text_field :author, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :Fecha_de_publicacion %>
            <%= f.date_field :published_at, class: "form-control" %>
          </div>

          <% unless @book.new_record? %>
            <div class="form-group">
              <%= f.label :Disponibilidad %>
              <%= f.select(:state, options_for_select(([[ 'Disponible', 'available'], [ 'No Disponible','not available']]), @book.state))%>
            </div>
          <% end %>
          

        </div>
        <div class="card-footer text-right">
          <%= link_to "Cancelar", books_path, class: "btn btn-outline-dark" %>
          <% if @book.new_record? %>
            <%= f.submit "Crear Libro" , class: "btn btn-success" %>
            <% else %>
            <%= f.submit "Guardar cambios" , class: "btn btn-secondary" %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/books/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to('Home', welcome_index_path, class:'nav-link sr-only') %>
      </li>
      <li class="nav-item">
        <%= link_to('Libros', books_path, class:'nav-link sr-only') %>
      </li>
      <li class="nav-item">
        <%= link_to('Préstamos', loans_path, class:'nav-link sr-only') %>
      </li>
      <li>
        <%= link_to('Salir', welcome_index_path, class:'btn btn-secondary') %>
      </li>
    </ul>
  </div>
</nav>

app/views/books/edit.html.erb
<%= render "books/form" %>

app/views/books/index.html.erb
<%= render "navegacion/navbar"%>

<!------------------------------- VISTA DE LIBROS ---------------------------------------->

<div class="books-page">
  <div class="container">
    <% if can? :create, Book %>
      <div class="text-right"><%= link_to "Agregar Libro", new_book_path, class: "btn btn-outline-primary rounded-0" %>
      </div>
    <% end %>
    <br></br>
    <h3> LIBROS </h3>

    <%= form_tag(books_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscar" %>
      <%= submit_tag "Buscar" %>
    <% end %>


    <% @books.each do |book| %>
    <div class="book card flex-sm-row align-items-center align-items-sm-start mt-5">
        <div class="card-body">
          <h5 class="card-title"> <strong><%= book.name %></strong> </h5>
          <h5><%= book.author %> </h5>
          <p class="card-text"> <%= book.available%></p>
          <%= link_to "Detalles", book, class: "btn btn-info" %>
          <% if can? :edit, book %>
            <%= link_to "Editar", edit_book_path(book), class: "btn btn-secondary" %>
          <% end %>
           <% if can? :delete, book %>
          <%= link_to "Eliminar", book, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
          <% end %>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= render "books/form" %>

app/views/books/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, books_path, class: "btn btn-link" %>

    <header class="main">
      <h2>Detalles del libro</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
   
      <div class="book-details">
        
        <dl>
          <dt>ISBN</dt>
          <dd><%= @book.isbn %></dd>
          <dt>Nombre</dt>
          <dd><%= @book.name %></dd>
          <dt>Autor</dt>
          <dd><%= @book.author %></dd>
          <dt>Clasificación</dt>
          <dd><%= @book.tag %></dd>
          <dt>Fecha de publicación</dt>
          <dd><%= @book.published_at %></dd>
          <dt>Disponibilidad</dt>
          <dd><%= @book.available %></dd>
        </dl>
        
      </div>
    </div>
  </div>
</div>