config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'loans/new'
  resources :books
  resources :users
  resources :loans



  # Session routes
	get 'login' => 'session#new'
	post 'login' => 'session#create'
	delete 'logout' => 'session#destroy'
	get 'logout' => 'session#destroy'

end

app/models/loan.rb
class Loan < ApplicationRecord
	belongs_to :user
	belongs_to :book

	before_validation :set_state, on: :create

##### BUSCADOR
	def self.search(search)
  		#where("user_id LIKE ?", "%#{search}%")
  		estados = where("state LIKE ?", "%#{search}%")
  		ids = where("id LIKE ?", "%#{search}%")
  		#names = Loan.includes(:user).where("user.last_name LIKE ?", "%#{search}%")
		Loan.from("(#{estados.to_sql} UNION #{ids.to_sql}) AS loans")

  	end
##### ESTADO POR DEFECTO
	def set_state
	    self.state = "actived"
	end
##### SEGÚN EL VALOR QUE SE INGRESA ES LO QUE SE VE
	def estado
		estados = {"actived" => "Activo", "expired" => "Expirado", "finished" => "Finalizado"}
		estados[self.state]
	end

##### CAMBIA LOS ESTADOS VENCIDOS AUTOMATICAMENTE
	def is_expired?
		if self.final_date < DateTime.now && self.state == "actived"
			self.state = "expired"
			self.save
		end
		self.state == "expired"
	end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
	before_action :find_loan, only: [:show,:edit,:update,:destroy]
 
  load_and_authorize_resource

 def index
    @loans = Loan.all
    @loans = @loans.map { |loan|loan.is_expired? }

    if params[:search]
      @loans = Loan.search(params[:search]).order("created_at DESC")
    else
      @loans = Loan.all.order('created_at DESC')
    end
  end

  def show
  end

  def new
    @loan = Loan.new
  end

  def create
    @book = Book.find_by_id(params[:loan][:book_id])

    if @book.available?
      puts loan_params
      
      @loan = Loan.new(loan_params)
      @loan.save
      redirect_to @loan
    else
      render plain: "Libro no disponible"
    end
  end

  def loan_params
      params.require(:loan).permit(:user_id, :book_id, :initiation_date, :final_date, :state)
  end

  def edit
  end

  def update
    if @loan.update(loan_params)
      redirect_to @loan
    else
      render :edit
    end
  end

  def destroy
    @loan.destroy
    redirect_to loans_path
  end

  def find_loan
    @loan = Loan.find(params[:id])
  end


end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<!------------------------------- FORMULARIO DE PRÉSTAMOS ---------------------------------------->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
        <% if @loan.new_record? %>
          <div class="card-header font-weight-bold">Agregar Préstamo</div>
        <% else %>
          <div class="card-header font-weight-bold">Editar Préstamo</div>
        <% end %>

          <%= form_for @loan do |f| %>
            <div class="card-body">
               <div class="form-group">
                <%= f.label :Usuario %>
                <%= f.select(:user_id, options_for_select(([nil]+User.all.pluck(:last_name, :id)), @loan.user_id))%>
              </div>
              <div class="form-group">
                <%= f.label :Libro %>
                <%= f.select(:book_id, options_for_select(([nil]+Book.all.pluck(:name, :id)), @loan.book_id))%>
              </div>
              <div class="form-group">
                <%= f.label :Desde %>
                <%= f.date_field :initiation_date, class: "form-control" %>
              </div>
              
              <div class="form-group">
                <%= f.label :Hasta %>
                <%= f.date_field :final_date, class: "form-control" %>
              </div>


              <% unless @loan.new_record? %>
               <div class="form-group">
                <%= f.label :Estado %><br>
                <%= f.select(:state, options_for_select(([[ 'Activo', 'actived'] , [ 'Expirado','expired'] , [ 'Finalizado', 'finished']]), @loan.state))%>
                </div>
              <% end %>

            </div>
            <div class="card-footer text-right">
              <%= link_to "Cancelar", loans_path, class: "btn btn-outline-dark" %>
              <% if @loan.new_record? %>
                <%= f.submit "Crear préstamo" , class: "btn btn-success" %>
              <% else %>
                <%= f.submit "Guardar cambios" , class: "btn btn-secondary" %>
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/loans/edit.html.erb
<%= render "loans/form" %>

app/views/loans/index.html.erb
<%= render "navegacion/navbar"%>

<!------------------------------- VISTA DE PRÉSTAMOS ---------------------------------------->

<div class="books-page">
  <div class="container">
    <% if can? :create, Loan %> <!-- Permiso -->
      <div class="text-right"><%= link_to "Nuevo Préstamo", new_loan_path, class: "btn btn-outline-primary rounded-0" %><!-- Botón nuevo préstamo -->
      </div>
    <% end %>
    <br></br>
    <h3> PRÉSTAMOS </h3>

<!--BUSCADOR -->
    <%= form_tag(loans_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscar Préstamos" %>
      <%= submit_tag "Buscar" %>
    <% end %>
<!--/BUSCADOR -->


<!--LISTADO DE PRÉSTAMOS -->   
    <% @loans.each do |loan| %>
  <% if can? :read, loan %> <!-- Permiso --> 
      <div class="book card flex-sm-row align-items-center align-items-sm-start mt-5">
          
          <div class="card-body">
            
            <h4 class="card-title">

            

              Préstamo ID #<strong><%= loan.id %></strong> Estado: <strong><%= loan.estado %></strong>
              <h5><strong><%= loan.book.name %></strong></h5>
              <h6> Retirado por: <strong><%= loan.user.last_name %> <%= loan.user.first_name %></strong> Usuario #<%= loan.user_id %></h6>
            </h4>
            <p class="card-text"> Vencimiento: <strong><%= loan.final_date %></strong></p>

            <%= link_to "Detalles", loan, class: "btn btn-info" %>

            

            <% if can? :edit, loan %> <!-- /Permiso -->
              <%= link_to "Editar", edit_loan_path(loan), class: "btn btn-secondary" %> 
            <% end %>

            <% if can? :delete, loan %> <!-- /Permiso -->
            <%= link_to "Eliminar", loan, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este préstamo?" } %>
            <% end %>
          
          </div>
        
      </div>
  <% end %>
    <% end %>
<!-- /LISTADO DE PRÉSTAMOS -->
  </div>
</div>

app/views/loans/new.html.erb
<%= render "loans/form" %>

app/views/loans/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, loans_path, class: "btn btn-black" %>

    <header class="main">
      <h2>Detalles del préstamo</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
   
      <div class="book-details">
        
        <dl>
          <dt>ID de préstamo</dt>
          <dd><%= @loan.id %></dd>	
          <dt>Libro</dt>
          <dd><%= @loan.book.isbn %> <%= @loan.book.name %></dd>
          <dt>Retirado por</dt>
          <dd><%= @loan.user.last_name%> <%= @loan.user.first_name %></dd>
          <dt>Desde</dt>
          <dd><%= @loan.initiation_date %></dd>
          <dt>Hasta</dt>
          <dd><%= @loan.final_date %></dd>
          <dt>Estado</dt>
          <dd><%= @loan.estado %></dd>
        </dl>
        
      </div>
    </div>
  </div>
</div>